# Generated by Django 4.1.1 on 2022-10-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_alter_product_image_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='merchant_id',
            new_name='payment_intent',
        ),
    ]
